# Use the Node.js base image
FROM node:20

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn install; \
  elif [ -f package-lock.json ]; then npm install; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Copy the application files
COPY . .

# Expose the development port
EXPOSE 3000

# Start the Prisma migration and then the Next.js dev server
CMD ["sh", "-c", "npx prisma db push && npm run dev"]
